behaviors:
  Boss:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 25600
      learning_rate: 0.00003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    even_checkpoints: false
    checkpoint_interval: 100000
    threaded: true
    max_steps: 10000000
    time_horizon: 1024
    summary_freq: 100000
    self_paly:
      save_steps: 200000
      team_change: 2000000
      swap_steps: 200000

  Player:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 25600
      learning_rate: 0.00003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    even_checkpoints: false
    checkpoint_interval: 100000
    threaded: true
    max_steps: 10000000
    time_horizon: 1024
    summary_freq: 100000
    self_paly:
      save_steps: 200000
      team_change: 2000000
      swap_steps: 200000